import TopNavbar from "@/components/TopNavbar";
import "./globals.css";
import { Tangerine,Josefin_Sans } from 'next/font/google'

export const tangerine = Tangerine({
  subsets: ['latin'],
  display: 'swap',
  weight:['400','700'],
  variable:'--font-tang'
})

export const josefin = Josefin_Sans({
  subsets: ['latin'],
  display: 'swap',
  weight:['100','200','300','400','500','600','700'],
  variable:'--font-josef'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">      
      <body>
        {/* <TopNavbar/> */}
        {children}
      </body>    
    </html>
  );
}
